stages:
  - build
  - deploy

# The build job
build:
  stage: build
  image: node:16  # Use the official Node.js image
  script:
    - npm ci    # Clean install dependencies
    - npm run build  # Build the Vite app
  artifacts:
    paths:
      - dist/    # Save the build artifacts in the `dist` folder

# The deploy job
deploy:
  stage: deploy
  image: busybox:1.35-uclibc  # A lightweight image for deploying
  script:
    - apt-get update && apt-get install -y ssh
    - echo "Deploying to server..."  # Your deployment command here
    - rsync -avz dist/ user@your-server:/path/to/deployment/directory  # Example using rsync to deploy
  only:
    - main  # Deploy only when pushing to the `main` branch