stages:
  - build
  - deploy

# Build step
build:
  stage: build
  image: node:16
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist/

# Deploy to GitLab Pages
pages:
  stage: deploy
  script:
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  only:
    - main